import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StairLoader from "@/components/StairLoader";
// import {
// 	Navbar,
// 	NavBody,
// 	NavItems,
// 	NavbarLogo,
// 	NavbarButton,
// } from '@/components/ui/resizable-navbar';

// const navItems = [
// 	{ name: 'About', link: '#about' },
// 	{ name: 'Docs', link: '#docs' },
// 	{ name: 'Pricing', link: '#pricing' },
// ];
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#020202] text-white`}
      >
        <StairLoader />
        {/* <Navbar>
                <NavBody>
                  <NavbarLogo />
                  <NavItems items={navItems} />
                  <NavbarButton href="#" variant="dark">Get started</NavbarButton>
                </NavBody>
              </Navbar> */}
        {children}
      </body>
    </html>
  );
}
